const BandZipActions = {
    UPLOAD: "UPLOAD",
    UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
    UPLOAD_FAILURE: "UPLOAD_FAILURE",
    FETCH_LATEST_HRV: "FETCH_LATEST_HRV",
    FETCH_LATEST_HRV_SUCCESS: "FETCH LATEST_HRV_SUCCESS",
    FETCH_LATEST_HRV_FAILURE: "FETCH_LATEST_HRV_FAILURE",
};

export default BandZipActions;
