const PHQActions = {
    FETCH_QUESTIONS: "FETCH_QUESTIONS",
    FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
    FETCH_QUESTION_FAILURE: "FETCH_QUESTIONS FAILURE",
    POST_ANSWER: "POST_ANSWER",
    POST_ANSWER_SUCCESS: "POST_ANSWER_SUCCESS",
    POST_ANSWER_FAILURE: "POST_ANSWER_FAILURE",
    FETCH_SCORE: "FETCH_SCORE",
    FETCH_SCORE_SUCCESS: "FETCH_SCORE_SUCCESS",
    FETCH_SCORE_FAILURE: "FETCH_SCORE_FAILURE",
    FETCH_DAILY_SCORES: "FETCH_DAILY_SCORES",
    FETCH_DAILY_SCORES_SUCCESS: "FETCH_DAILY_SCORES_SUCCESS",
    FETCH_DAILY_SCORES_FAILURE: "FETCH_DAILY_SCORES_FAILURE",
};

export default PHQActions;
