const ApprovalActionTypes = {
    FETCH_APPROVAL_REQUESTS: "FETCH_APPROVAL_REQUEST ",
    FETCH_APPROVAL_REQUESTS_SUCCESS: "FETCH_APPROVAL_REQUEST_SUCCESS",
    FETCH_APPROVAL_REQUESTS_FAILURE: "FETCH_APPROVAL_REQUEST_FAILURE",
    APPROVE_REQUEST: "APPROVE_REQUEST",
    APPROVE_REQUEST_SUCCESS: "APPROVE_REQUEST_SUCCESS",
    APPROVE_REQUEST_FAILURE: "APPROVE_REQUEST_FAILURE",
};
export default ApprovalActionTypes;
