const UserActionTypes = {
    FETCH_USER_SELF: "FETCH_USER_SELF",
    FETCH_USER_SELF_SUCCESS: "FETCH_USER_SELF_SUCCESS",
    FETCH_USER_SELF_FAILURE: "FETCH_USER_SELF_FAILURE",
    FETCH_USER: "FETCH_USER",
    FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
    FETCH_USER_FAILURE: "FETCH_USER_FAILURE",
    FETCH_USERS: "FETCH_USERS",
    FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
    UPDATE_USER: "UPDATE_USER",
    UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
    UPDATE_USER_FAILURE: "UPDATE_USER_FAILURE",
};

export default UserActionTypes;
